import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import genshin from 'genshin-api'

export default function getCharacter({ char }) {
  const charImg = char.name.toLowerCase(); //API fetch needs everything in lower case
  //console.log(charImg);
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Genshin Impact Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

    <Image src={`https://api.genshin.dev/characters/${charImg}/gacha-splash`} alt="character portrait" width={750} height={750} />
      <h1>Character Details</h1>

     

    </div>
  );7
}

export async function getServerSideProps({params}) {
    const charName = params.name.toLowerCase() //Gets character name
    
    //API fetch
    const req = await fetch(`https://api.genshin.dev/characters/${charName}`)
    const data = await req.json()
    return {
        props: {
            char: data
        }
    }
}
