import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import liyue from '../../public/liyue.jpg';

export default function getCharacter({ char }) {
  const charImg = char.name.toLowerCase(); //API fetch needs everything in lower case
  console.log(char.title);
  return (
    <>
      <div className={styles.wrapper} style={{backgroundImage: '/inazuma.pngs'}}>
        <Head>
          <title>Genshin Impact Index</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>

      
            <Image src={liyue} alt='background character image' width={100} height={100}/>
       

        <h1>Character Details</h1>
        <h2>Name: {char.name}</h2>
        <h2>Title: {char.title}</h2>
        <h2>Element: {char.vision}</h2>
        <h2>Affiliation: {char.nation}</h2>
        <h2>
          Rarity: {char.rarity}
          <Image src={"/starIcon.png"} alt="starIcon" width={28} height={20} />
        </h2>



        <Image
          src={`https://api.genshin.dev/characters/${charImg}/gacha-splash`}
          alt="character portrait"
          width={750}
          height={750}
        />
      </div>
    </>
  );
}



export async function getServerSideProps({params}) {
    const charName = params.name.toLowerCase() //Gets character name
    
    //API fetch
    const req = await fetch(`https://api.genshin.dev/characters/${charName}`)
    const data = await req.json()
    return {
        props: {
            char: data
        }
    }
}
