import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Character.module.css'

export default function getCharacter({ char }) {
  const charImg = char.name.toLowerCase(); //API fetch needs everything in lower case
  console.log(char);
  return (
    <>
         <div className={styles.wrapper}>
        <Head>
          <title>Genshin Impact Index</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>

        <h1>Character Details</h1>
        <h2>Name: {char.name}</h2>
        <h2>Title: {char.title}</h2>
        <h2>Element: {char.vision}</h2>
        <h2>Affiliation: {char.nation}</h2>
        <h2>
          Rarity: {char.rarity}
          <Image src={"/starIcon.png"} alt="starIcon" width={28} height={20} />
        </h2>
        <h2>Weapon: {char.weapon}</h2>

        <div>
          <Image
            src={`https://api.genshin.dev/characters/${charImg}/portrait`}
            alt="character portrait"
            width={250}
            height={250}
            style={{display: 'flex', justifyContent: 'flex-end'}}
          />
        </div>
      </div>
    </>
  );
}



export async function getServerSideProps({params}) {
    const charName = params.name.toLowerCase() //Gets character name
    
    //API fetch
    const req = await fetch(`https://api.genshin.dev/characters/${charName}`)
    const data = await req.json()
    return {
        props: {
            char: data
        }
    }
}
