import React, {useRef} from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Character.module.css'
import { useRouter } from 'next/router';

export default function CharacterList({ res }) {
    const input = useRef("")
    const router = useRouter();
    //console.log(charData)

  if (res.length > 0) {
    return (
      <div className={styles.wrapper}>
        <Head>
          <title>Genshin Impact Index</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <div>
        <div>
          <h2>
            Character Directory
          </h2>
        </div>
          {res.map((char, index) => {
            // const charName = char.toUpperCase();
            // const charIcon = res[index];
            //console.log(res[0])
            //const charIcon = res[char].name.toLowerCase();
            return (
              <>
                <div className={styles.charContainer}>
                  <div className={styles.charBorder}>
                    <div className={styles.charGrid}>
                      <Image
                        style={styles.charImg}
                        src={`https://api.genshin.dev/characters/${char}/icon-big`}
                        alt="character icons"
                        width={100}
                        height={100}
                      />
                      <p key={index}>{char.toUpperCase()}</p>
                    </div>
                  </div>
                  <div></div>
                  <div className={styles.charDetails}>
                    <button
                      type="submit"
                      onClick={() => {
                        router.push(`/characters/${char}`);
                      }}
                    >
                      Character Details
                    </button>
                  </div>
                </div>
              </>
            );
          })}
        </div>
      </div>
    );
  } else {
    return <h1>Did not find!</h1>;
  }
}

CharacterList.getInitialProps = async () => {
  const req = await fetch("https://api.genshin.dev/characters");
  const data = await req.json();
  return { res: data };
};

