import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function CharacterList({ res }) {
  console.log(res[5]);
  if (res.length > 0) {
    return (
      <div className={styles.wrapper}>
        <Head>
          <title>Genshin Impact Index</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <h1>Available Characters</h1>
        <div>
          {res.map((char, index) => {
            return (
              <>
              <div>
                <button className={styles.wrapper}>
                  <p key={index}>{char}</p>
                </button>
              </div>
              </>
            );
          })}
        </div>
      </div>
    );
  } else {
    return <h1>Did not find!</h1>;
  }
}

CharacterList.getInitialProps = async () => {
  const req = await fetch("https://api.genshin.dev/characters");
  const data = await req.json();
  return { res: data };
};

