import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Genshin Impact Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      
      <div className={styles.landingContainer}>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Genshin Impact Character Index
        </h1>

        <p className={styles.description}>
          A website for information on characters
        </p>

      <div className={styles.allButton}>
          <Link href="/characters">Checkout characters!</Link>
      </div>

        <div className={styles.grid}>
          
        </div>
      </main>
      </div>
      

    </div>
  )
}

